{% set name = "parallel-bilby" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parallel_bilby-{{ version }}.tar.gz
  sha256: 4bb0b954ceef18c649e2b57fdf0dde4e196dd484f573c99ad4db66604575b616

build:
  number: 0
  noarch: python
  entry_points:
    - parallel_bilby_generation=parallel_bilby.generation:main
    - parallel_bilby_analysis=parallel_bilby.analysis:main
    - parallel_bilby_ptemcee_analysis=parallel_bilby.ptemcee_analysis:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - bilby >=1.1.1
    - bilby_pipe >=1.0.3
    - corner
    - dynesty >=1.0.0
    - future
    - gwpy
    - matplotlib-base
    - mpi4py >3.0.0
    - nestcheck
    - numpy
    - pandas
    - python >=3.5
    - schwimmbad
    - scipy >=1.2.0
    - tqdm

test:
  imports:
    - parallel_bilby
    #- parallel_bilby.analysis
    - parallel_bilby.generation
    - parallel_bilby.parser
    #- parallel_bilby.ptemcee_analysis
    - parallel_bilby.schwimmbad_fast
    - parallel_bilby.slurm
    - parallel_bilby.utils
  requires:
    - openssh  # [linux]
    - pip
    - ptemcee
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - parallel_bilby_generation --help
    - parallel_bilby_analysis --help
    - parallel_bilby_ptemcee_analysis --help

about:
  home: https://lscsoft.docs.ligo.org/parallel_bilby/
  dev_url: https://git.ligo.org/lscsoft/parallel_bilby
  doc_url: https://lscsoft.docs.ligo.org/parallel_bilby/
  summary: Running bilby at scale
  license: MIT
  license_file: LICENSE
  description: |
    A python package to run gravitational wave inference analyses on
    multiple cores of a machine using their message passing interface (MPI).

extra:
  recipe-maintainers:
    - avivajpeyi
    - duncanmmacleod
    - GregoryAshton
